#!/bin/bash
MHOME=$HOME
# echo ${MHOME}
if [ ! -d $HOME/ldif ] ; then mkdir ${MHOME}/ldif ; fi
if [ ! -d $HOME/passwd ] ; then mkdir ${MHOME}/passwd ; fi
klist -s || kinit
IFS='
'
if test -z "$2" ; then echo "$0 username lab"; exit ; fi
OU=Users,OU=SciComp
# URI='OU=Departments,OU=Domain Members,DC=med,DC=upenn,DC=edu'
URI='OU=PMACS,DC=pmacs,DC=upenn,DC=edu'
maildomain=upenn.edu
# Description="Hematology-Oncology Cancer Biology user"
# Description="$3"
GROUPCAT='CN=Group,CN=Schema,CN=Configuration,DC=pmacs,DC=upenn,DC=edu'
GROUPADD='CN=CGACTAccess,OU=Groups,OU=SciComp,OU=PMACS,DC=pmacs,DC=upenn,DC=edu'
if test -n "$1" ; then NEWUSER="$1" ; fi
if test -n "$2" ; then GECOS="$2" ; fi
INPUT=${NEWUSER}.passwd
CREATE="${INPUT}.ldif"
MODIFY="${INPUT}_mod.ldif"
CLUST="${INPUT}_clust.ldif"

LDIR=ldif
TDIR=tmp
PDIR=passwd
ADHOST=smithers.pmacs.upenn.edu
NEWID=`getnewid.sh`
SHELL=/bin/bash
NHOME=/home/$NEWUSER
echo $INPUT $GECOS $NEWID $SHELL $NHOME
echo "$NEWUSER:"'*'":$NEWID:$NEWID:$GECOS:$NHOME:$SHELL"
echo "$NEWUSER:"'*'":$NEWID:$NEWID:$GECOS:$NHOME:$SHELL" > "${MHOME}/${PDIR}/${INPUT}"
INPUT="${MHOME}/${PDIR}/${INPUT}"
echo $INPUT

CREATE="${MHOME}/${LDIR}/$CREATE"
MODIFY="${MHOME}/${LDIR}/$MODIFY"
CLUST="${MHOME}/${LDIR}/$CLUST"
UGroup="${MHOME}/${LDIR}/$UGroup"
UNIX=Y
# rm -rf $MODIFY $CREATE $CLUST $UGroup
echo $MODIFY $CREATE $CLUST $UGroup
# exit

# read the input file and make the fields
for i in `cat $INPUT` ; do 
uname=`echo $i|awk -F: '{print $1}'`; 
uid=`echo $i|awk -F: '{print $3}'`;
gid=`echo $i|awk -F: '{print $4}'`;


CN="CN=$gcos,OU=$OU,$URI";
done

# echo CREATE SECTION $uname
# echo MOD SECTION $uname
#make unique usergroup
#put in  cluster

echo put in clustergroup SECTION $uname
IFS='
'
for i in `grep dn: $CREATE|awk -F: '{print $2}'` ; do 
echo dn: $GROUPADD >> $CLUST
echo changetype: modify>> $CLUST
echo add: member>> $CLUST
echo member: $i>> $CLUST
echo "" >> $CLUST
done

echo add to group $5 SECTION $uname
if test -n "$2" ; then
LAB=$2
GMODIFY="${NEWUSER}_labmod.ldif"
GMODIFY="${MHOME}/${LDIR}/$GMODIFY"
# if [ -r "${MHOME}/${LDIR}/$GMODIFY" ] ; then rm "${MHOME}/${LDIR}/$GMODIFY" ; fi
GCN=`ldapsearch -LLL -Q -b OU=PMACS,DC=pmacs,DC=upenn,DC=edu CN=$LAB|grep dn:`

if test -n "$GCN" ; then
	/bin/echo -e "$GCN\nchangetype: modify\nadd: member\nmember: $CN\n" > $GMODIFY
	else
	echo "$LAB does not exist "
exit
fi
fi


# echo create users unix group

# echo add users to a group
echo ldapmodify -c -h $ADHOST -f $CLUST
echo ldapmodify -c -h $ADHOST -f $CLUST >> ${MHOME}/runmkuser.sh

# echo add users to a lab

echo ldapadd -c -h $ADHOST -f $GMODIFY
echo ldapadd -c -h $ADHOST -f $GMODIFY >> ${MHOME}/runmkuser.sh

echo sudo sss_cache -G -d PMACS >> ${MHOME}/runmkuser.sh
echo groups $uname >> ${MHOME}/runmkuser.sh

chmod 755 ${MHOME}/runmkuser.sh
ans=$3

